# Generated by Django 5.2 on 2025-04-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMIapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmi',
            name='email',
        ),
        migrations.AddField(
            model_name='bmi',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bmi',
            name='bmi_status',
            field=models.CharField(default='NOT YET', max_length=30),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
